---

- name: install spack prerequisites
  package:
    name: git,python3,make,tar,gzip,bzip2,xz,zstd,patch,curl,unzip

- name: install system-package-manager compiler packages
  package:
    name: "{{ item.system_pkg }}"
  loop: "{{ spack_system_compilers }}"

- name: clone spack repo
  git:
    repo: https://github.com/spack/spack.git
    dest: "{{ spack_root }}"
    version: "{{ spack_version }}"
    depth: "1"
  run_once: true

- name: add system-package-manager compilers to spack # NB added to root's spack config so installs must use become
  shell:
    cmd: "module load {{ item.module }} && {{ spack_cmd }} compiler find" # TODO: idempotent
    executable: "/usr/bin/bash"
  register: compiler_find
  changed_when: "'Found no new compilers' not in compiler_find.stdout"
  loop: "{{ spack_system_compilers }}"
  environment:
    BASH_ENV: /opt/ohpc/admin/lmod/lmod/init/bash 
    MODULEPATH: /opt/ohpc/pub/modulefiles
  run_once: true

- name: find user's home directory
  shell:
    cmd: "getent passwd {{ item }} | cut -d ':' -f 6"
  loop: "{{ spack_users }}"
  register: spack_user_homedirs

- name: modify users .bashrc
  blockinfile:
    path: "{{ item.stdout }}/.bashrc"
    create: false
    block: |
      export SPACK_ROOT={{ spack_root }}
      . $SPACK_ROOT/share/spack/setup-env.sh
      module use $SPACK_ROOT/share/spack/lmod/linux*/Core/
    insertafter: "# User specific aliases and functions"
  loop: "{{ spack_user_homedirs.results }}"
  run_once: true # NB: assumes home is on shared filesystem if role run on multiple hosts

- name: create spack modules config
  template:
    dest: "{{ spack_root }}/etc/spack/modules.yaml"
    src: templates/modules.j2
  run_once: true

- name: install spack packages
  shell:
    cmd: "{{ spack_cmd }} install {{ item }}"
  loop: "{{ spack_packages }}"
  register: spack_install
  failed_when: "'failed' in spack_install.stderr or spack_install.rc != 0"
  changed_when: "'Installing' in spack_install.stdout"
  run_once: true

- name: create module tree
  shell:
    cmd: "{{ spack_cmd }} module lmod refresh -y" # TODO: idempotency? think we'd have to hash the tree or something
  run_once: true
